version: "3.8"

services:
  pair-pilot-mcp:
    container_name: pair-pilot
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8100:8100"
    networks:
      - dev-network
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8100

networks:
  dev-network:
    driver: bridge
