services:
  devcontainer:
    container_name: devcontainer-pair-pilot-mcp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pair-pilot-mcp:
    container_name: pair-pilot
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=8100
